# Generated by Django 4.1.2 on 2023-02-26 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=50, verbose_name='Язык')),
            ],
            options={
                'verbose_name': 'Язык',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_word', models.CharField(max_length=100, verbose_name='Русское слово')),
                ('foreign_word', models.CharField(max_length=100, verbose_name='Иностранное слово')),
                ('context', models.CharField(max_length=100, verbose_name='Контекст')),
                ('asking_date', models.DateField(verbose_name='Дата повторения')),
                ('box_number', models.IntegerField(default=1, verbose_name='Номер коробки')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionary.language')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
    ]
