# Generated by Django 4.1.2 on 2023-09-10 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words',
            name='asking_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата повторения'),
        ),
        migrations.AlterField(
            model_name='words',
            name='box_number',
            field=models.IntegerField(default=0, verbose_name='Номер коробки'),
        ),
    ]
