# Generated by Django 4.1.2 on 2024-03-28 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0002_alter_words_asking_date_alter_words_box_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="language",
            name="language_code",
            field=models.CharField(
                default="en", max_length=10, verbose_name="Код языка"
            ),
        ),
    ]
