# Generated by Django 4.1.2 on 2024-04-06 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dictionary", "0003_language_language_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="words",
            name="context",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Контекст"
            ),
        ),
    ]
