# Generated by Django 4.1.2 on 2023-02-26 17:12

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServicePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "text",
                    tinymce.models.HTMLField(blank=True, verbose_name="Текст страницы"),
                ),
                (
                    "page_type",
                    models.CharField(
                        choices=[
                            ("user_agreement", "Пользовательское соглашение"),
                            ("privacy_policy", "Политика конфиденциальности"),
                            ("404", "Ошибка 404"),
                            ("500", "Ошибка 500"),
                            ("test_completed", "Тренеровка завершена"),
                            ("password_reset_complete", "Пароль успешно сброшен"),
                            ("password_reset_done", "Сброс пароля по почте"),
                            ("password_change_done", "Парроль успешно изменен"),
                        ],
                        max_length=30,
                        unique=True,
                        verbose_name="Тип страницы",
                    ),
                ),
            ],
            options={
                "verbose_name": "Служебная страница",
                "verbose_name_plural": "Служебные страницы",
            },
        ),
    ]
