# Generated by Django 4.1.2 on 2023-02-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField(blank=True, verbose_name='Текст страницы')),
                ('page_type', models.CharField(choices=[('service_page', 'Пользовательское соглашение'), ('privacy_policy', 'Политика конфиденциальности'), ('404', 'Страница 404'), ('password_reset_complete', 'Успешная смена пароля'), ('password_reset_done', 'Сброс пароля'), ('success_text_page', 'Тренеровка завершена')], max_length=30, verbose_name='Тип страницы')),
            ],
            options={
                'verbose_name': 'Служебная страница',
                'verbose_name_plural': 'Служебные страницы',
            },
        ),
    ]
