# Generated by Django 4.1.2 on 2023-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='page_type',
            field=models.CharField(choices=[('user_agreement', 'Пользовательское соглашение'), ('privacy_policy', 'Политика конфиденциальности')], max_length=30, unique=True, verbose_name='Тип страницы'),
        ),
    ]
