# Generated by Django 4.1.2 on 2023-03-17 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import text_books.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TextBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('book_file', models.FileField(upload_to=text_books.models.TextBook.user_directory_path)),
                ('keys_file', models.FileField(blank=True, null=True, upload_to=text_books.models.TextBook.user_directory_path)),
                ('preview_image', models.ImageField(upload_to=text_books.models.TextBook.user_directory_path)),
                ('current_page_number', models.IntegerField(default=1)),
                ('keys_page_number', models.IntegerField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateField()),
                ('text', models.TextField()),
                ('page_number', models.IntegerField()),
                ('keys_page_number', models.IntegerField()),
                ('text_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='text_books.textbook')),
            ],
            options={
                'ordering': ['-page_number'],
            },
        ),
    ]
