# Generated by Django 4.1.2 on 2023-02-26 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "slug",
                    models.SlugField(max_length=255, unique=True, verbose_name="Слаг"),
                ),
                ("text", models.TextField(verbose_name="Текст статьи")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Дата публикации",
                    ),
                ),
                (
                    "is_main_page",
                    models.BooleanField(
                        default=False, verbose_name="Главная страница?"
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(default=False, verbose_name="Опублковать?"),
                ),
                (
                    "preview_photo",
                    models.ImageField(
                        upload_to="photos/%Y/%m/%d", verbose_name="Фото превью"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статьи",
                "verbose_name_plural": "Статьи",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, verbose_name="Имя")),
                ("email", models.EmailField(max_length=100, verbose_name="E-mail")),
                (
                    "text",
                    models.TextField(
                        max_length=1000,
                        verbose_name="Текст (максимальная длина комментария 1000 символов)",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Оставлен"
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Активный")),
                (
                    "article",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="articles.article",
                        verbose_name="Статья",
                    ),
                ),
            ],
            options={
                "verbose_name": "Комментарий",
                "verbose_name_plural": "Комментарии",
                "ordering": ("-created",),
            },
        ),
    ]
