# Generated by Django 4.1.2 on 2024-04-10 21:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import reader.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dictionary", "0004_alter_words_context"),
        ("reader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PDFBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                (
                    "book_file",
                    models.FileField(
                        upload_to=reader.models.PDFBook.user_directory_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                (
                    "preview_image",
                    models.ImageField(
                        upload_to=reader.models.PDFBook.user_directory_path
                    ),
                ),
                ("current_page_number", models.IntegerField(default=1)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="dictionary.language",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
    ]
